apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-import-variables
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: import-variables
          image: {{ .Values.airflowChart.airflow.image.repository }}:{{ .Values.airflowChart.airflow.image.tag }}
          envFrom:
            - secretRef:
                name: airflow-config-envs
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-shared-secrets
                  key: airflow-password
            # Disable remote logging so this job doesn't need apache-airflow-providers-amazon
            - name: AIRFLOW__LOGGING__REMOTE_LOGGING
              value: "False"
          volumeMounts:
            - name: variables-file
              mountPath: /tmp/variables.json
              subPath: variables.json
          command: ["/bin/bash", "-c"]
          args:
            - |
              airflow variables import /tmp/variables.json
      volumes:
        - name: variables-file
          secret:
            secretName: airflow-variables
      restartPolicy: OnFailure
