apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  fernet-key: "T3Blbk1ldGFkYXRhMTIzNDU2Nzg5MA==" # Clé stable pour le déploiement
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  webserver-secret-key: "OpenMetadataWebserverKey12345678"
