apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  fernet-key: "T3Blbk1ldGFkYXRhMTIzNDU2Nzg5MA=="
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  webserver-secret-key: "OpenMetadataWebserverKey12345678"
---
# PostgreSQL credentials for Airflow
apiVersion: v1
kind: Secret
metadata:
  name: postgres-shared-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  airflow-password: "airflow_pass"
