apiVersion: v1
kind: Secret
metadata:
  name: airflow-variables
  namespace: {{ .Release.Namespace }}
  labels:
    app: airflow
type: Opaque
stringData:
  # Format JSON pour importer plusieurs variables d'un coup
  variables.json: |
    {
      "openmetadata_jwt_token": "eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6ImluZ2VzdGlvbi1ib3QiLCJyb2xlcyI6WyJJbmdlc3Rpb25Cb3RSb2xlIl0sImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVuLW1ldGFkYXRhLm9yZyIsImlzQm90Ijp0cnVlLCJ0b2tlblR5cGUiOiJCT1QiLCJpYXQiOjE3NjczMjU0MzUsImV4cCI6bnVsbH0.IaXHTidmPOku_3Q9wWNaGJ7HNCR6LHleZnklnW8JZ5GoWZsckKfTpKK9wTMd3ULt8nNIA-64e-KEJQ8xuNu3ZINwjyDFEr6w_gAl9DpaCYkwSacUzSbn1q9JtflCjxCSHOmnx8MI8Gsx0gjxlgBIQo7vf7U5bxMO3ahNcpiq5_nsZiCn-qq2tuZ3cup6wRaNkpBSyk34J-t2LMRsu-4veKViHSVzqhfUMcOgFpvGK2wugYv7gJ-i7NV1T4osGrQk_fD1DXeIlJRA5hJLqGl-5lGj1_2qZ60E-WqYG6tDdApLtNz-i8hIIlzlTt7Bv_t_pTMA1qXGJpI_R5iqFBL6LA"
    }
