apiVersion: v2
name: postgres-shared
description: Shared PostgreSQL for Data Platform
type: application
version: 0.1.0
appVersion: "15"
dependencies:
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
