apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ibrahimlahouar/argocd.git
    path: charts/minio
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ibrahimlahouar/argocd.git
    path: charts/vault
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ibrahimlahouar/argocd.git
    path: charts/trino
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ibrahimlahouar/argocd.git
    path: charts/headlamp
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ibrahimlahouar/argocd.git
    path: charts/harbor
    targetRevision: main
    helm:
      values: |
        expose:
          type: nodePort
          tls:
            enabled: false
          nodePort:
            ports:
              http:
                nodePort: 30500
              https:
                nodePort: 30501
        externalURL: http://10.10.0.101:30500
        harborAdminPassword: "Harbor123!"
        chartmuseum:
          enabled: false
        notary:
          enabled: false
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              storageClass: local-path
              size: 100Gi
            jobservice:
              jobLog:
                storageClass: local-path
                size: 20Gi
              scanDataExports:
                storageClass: local-path
                size: 20Gi
            database:
              storageClass: local-path
              size: 20Gi
            redis:
              storageClass: local-path
              size: 8Gi
            trivy:
              storageClass: local-path
              size: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ibrahimlahouar/argocd.git
    path: charts/spark-operator
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata-dependencies
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ibrahimlahouar/argocd.git
    path: charts/openmetadata-dependencies
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: openmetadata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ibrahimlahouar/argocd.git
    path: charts/openmetadata
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: openmetadata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
