{{- $domain := .Values.domain }}
{{- $tls := .Values.tls }}
{{- $ingressClassName := .Values.ingressClassName }}

{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-ingress
  namespace: {{ $svc.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $tls.clusterIssuer }}
    {{- if $svc.annotations }}
    {{- range $key, $value := $svc.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ $ingressClassName }}
  {{- if $tls.enabled }}
  tls:
    - hosts:
        - {{ $svc.host }}.{{ $domain }}
      secretName: {{ $name }}-tls
  {{- end }}
  rules:
    - host: {{ $svc.host }}.{{ $domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $svc.serviceName }}
                port:
                  number: {{ $svc.servicePort }}
{{- end }}
{{- end }}

