apiVersion: v2
name: ingress-nginx
description: NGINX Ingress Controller for Kubernetes
type: application
version: 4.11.3
appVersion: "1.11.3"

dependencies:
  - name: ingress-nginx
    version: 4.11.3
    repository: https://kubernetes.github.io/ingress-nginx

