apiVersion: v2
name: spark-operator
description: Kubernetes Operator for Apache Spark
type: application
version: 1.0.0
appVersion: "v1beta2-1.3.8-3.1.1"
keywords:
  - spark
  - big-data
  - analytics
  - operator
home: https://github.com/kubeflow/spark-operator
sources:
  - https://github.com/kubeflow/spark-operator
maintainers:
  - name: Data Platform Team
    email: team@example.com
