# Secret pour le mot de passe DB OpenMetadata (PostgreSQL)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-shared-secrets
type: Opaque
stringData:
  openmetadata-password: "openmetadata_password"
---
# Secret Airflow (pour pipelineServiceClientConfig)
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
stringData:
  openmetadata-airflow-password: "admin"
