apiVersion: v2
name: airflow
description: Airflow - The Workflow Orchestra
type: application
version: 0.1.0
appVersion: "2.8.0"
dependencies:
  - name: airflow
    version: 1.11.0 # Correspond Ã  Airflow 2.7.x
    repository: https://airflow.apache.org
