apiVersion: v2
name: airflow
description: A Helm chart for Airflow Service
type: application
version: 1.0.0
appVersion: 2.7.3
dependencies:
  - name: airflow
    version: 8.9.0
    repository: https://airflow-helm.github.io/charts
    alias: airflowChart