{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openmetadata-ai-agent.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "openmetadata-ai-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
