apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  policyTypes:
  - Ingress
  ingress:
  # Airflow
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: airflow
    ports:
    - protocol: TCP
      port: 5432
  # OpenMetadata
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openmetadata
    ports:
    - protocol: TCP
      port: 5432
  # Harbor
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: harbor
    ports:
    - protocol: TCP
      port: 5432
  # Nessie
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nessie
    ports:
    - protocol: TCP
      port: 5432
  # Trino
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: trino
    ports:
    - protocol: TCP
      port: 5432
  # Velero / db-backups
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: velero
    ports:
    - protocol: TCP
      port: 5432