{{- if .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"10.10.0.101:30500\":{\"username\":\"admin\",\"password\":\"Harbor123!\",\"auth\":\"%s\"}}}" (printf "admin:Harbor123!" | b64enc) | b64enc }}
{{- end }}

