apiVersion: v2
name: opensearch
description: A Helm chart for OpenSearch Service
type: application
version: 1.0.0
appVersion: 2.11.1
dependencies:
  - name: opensearch
    version: 2.12.2
    repository: https://opensearch-project.github.io/helm-charts/
